# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: PQyg7aTzHvOANha20FH1WedcDeRtkojm
            client-secret: 25m6JxfF9gFyNna59I9bNdOwM45AIVEahpYZQYyGiZQrMA7jNdc3Sd1luGLcFUgQ
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-qrmxq-1u.us.auth0.com/